CREATE TABLE IF NOT EXISTS MIGRATION_MODEL
(
    `ID`         Utf8 NOT NULL,
    `VERSION`    Utf8,
    `UPDATE_TIME` Int64 NOT NULL DEFAULT 0,

    INDEX UK_MIGRATION_VERSION GLOBAL UNIQUE SYNC ON (`VERSION`),
    INDEX UK_MIGRATION_UPDATE_TIME GLOBAL UNIQUE SYNC ON (`UPDATE_TIME`),
    PRIMARY KEY (`ID`)
);
